name: "hot3d"
eval_name: "grab"
root: "data/hot3dgaze"
obj_root: "data/hot3d/processed_object_meshes"
instance_path: "data/hot3dgaze/instance.json"
data_path: "data/hot3d/data.npz"
data_obj_pc_path: "data/hot3d/obj.pkl"
balance_weights_path: "data/hot3d/balance_weights.pkl"
annt_json: "data/hot3d/annt.json"
text_json: "data/hot3d/text.json"
t2l_json: "data/hot3d/text_length.json"
t2c_json: "data/hot3d/text_count.json"
flat_hand: True
max_frames: 300
data_ratio: 1
augm: False
data_num: 101
text_num: 110